name: clang-format code

on: [ push ]

jobs:
    Linux:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Run clang-format
                uses: DoozyX/clang-format-lint-action@v0.13
                with:
                    source: 'test src src/DataStructure src/DataStructure/Bitmap src/DataStructure/Example'
                    exclude: ''
                    extensions: 'h,hpp,c,cc,cxx,cpp'
                    clangFormatVersion: 14
                    style: file
                    inplace: True

            -   name: Git commit format changes
                uses: EndBug/add-and-commit@v4
                with:
                    author_name: Clang Robot
                    author_email: robot@example.com
                    message: 'style: committing clang-format changes'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
