name: Catch2 Test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Conan
                uses: turtlebrowser/get-conan@v1.0

            -   name: Install package
                run: conan install ${{github.workspace}} -if=${{github.workspace}}/build

            -   name: Setup Ninja
                uses: ashutoshvarma/setup-ninja@master
                with:
                    version: 1.10.0

            -   name: CMake Build
                uses: ashutoshvarma/action-cmake-build@master
                with:
                    build-dir: ${{github.workspace}}/build
                    source-dir: ${{github.workspace}}
                    cc: gcc
                    cxx: g++
                    configure-options: -G Ninja
                    build-type: Release
                    parallel: 12

            -   name: Run Test
                run: ${{github.workspace}}build/test/test




