name: Catch2 Test

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Conan
                uses: turtlebrowser/get-conan@v1.0

            -   name: Install package
                run: conan install ${{ runner.workspace }} -if=${{ runner.workspace }}/build

            -   name: Setup Ninja
                uses: ashutoshvarma/setup-ninja@master
                with:
                    version: 1.10.0

            -   name: Build with CMake
                uses: ashutoshvarma/action-cmake-build@master
                with:
                    build-dir: ${{ runner.workspace }}/build
                    cc: gcc
                    cxx: g++
                    configure-options: -G Ninja
                    build-type: Release
                    parallel: 12

            -   name: Test
                run: ./build/test/test




